name: Brakar
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070711'
    - '#d9c298'
    - '#ad9161'
    - '#473948'
    - '#fefaef'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
