typography_spectrum: 0.56301
color:
  brandColors:
    - '#070711'
    - '#d9c298'
    - '#ad9161'
    - '#473948'
    - '#fefaef'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Brakar
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: I am brakar
description: aka the good guy
purpose: []
