name: Brakar
favicon: null
layout_spectrum: 0.13989705592393875
typography_spectrum: 0.47988883475773036
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7703444499056786
  lightness: 0.5559937262441963
  saturation: 0.7195070160087198
  rhythmicContrast: 0.5361330842133611
purpose: []
